version: "3.9" # Docker-compose version, just using the latest for now
services: 
  plume_base: # Name of the service, can be whatever you want
    build: # The . here is similar to the docker build . which specifiy the context in which to build the docker image under
      context: .
    volumes:
    - ./:/src # Left hand is host, right hand is container. Basically map an outside volume into container
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0', '1']
            capabilities: [gpu]
  #   # env_file:
